# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rfcontrol.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rfcontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frfcontrol.proto\x12\trfcontrol\"[\n\x08RFConfig\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x01\x12\x0c\n\x04gain\x18\x03 \x01(\x01\x12\x0c\n\x04mode\x18\x04 \x01(\t\x12\r\n\x05power\x18\x05 \x01(\x01\"\"\n\rDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x85\x01\n\nRFResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rdevice_status\x18\x03 \x01(\t\x12+\n\x0e\x63urrent_config\x18\x04 \x01(\x0b\x32\x13.rfcontrol.RFConfig\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\xa4\x01\n\x12\x44\x65viceInfoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x15\n\rserial_number\x18\x05 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x06 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x07 \x03(\t2\xdd\x01\n\x10RFControlService\x12;\n\rSetRFSettings\x12\x13.rfcontrol.RFConfig\x1a\x15.rfcontrol.RFResponse\x12\x42\n\x0fGetDeviceStatus\x12\x18.rfcontrol.DeviceRequest\x1a\x15.rfcontrol.RFResponse\x12H\n\rGetDeviceInfo\x12\x18.rfcontrol.DeviceRequest\x1a\x1d.rfcontrol.DeviceInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rfcontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RFCONFIG']._serialized_start=30
  _globals['_RFCONFIG']._serialized_end=121
  _globals['_DEVICEREQUEST']._serialized_start=123
  _globals['_DEVICEREQUEST']._serialized_end=157
  _globals['_RFRESPONSE']._serialized_start=160
  _globals['_RFRESPONSE']._serialized_end=293
  _globals['_DEVICEINFORESPONSE']._serialized_start=296
  _globals['_DEVICEINFORESPONSE']._serialized_end=460
  _globals['_RFCONTROLSERVICE']._serialized_start=463
  _globals['_RFCONTROLSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
